services: mongodb
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.7.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: 2.4.0
    - rvm: ruby-head
    - rvm: jruby-head
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - Gemfile
